global:
  root-url: http://dsi-7.univ-rouen.fr
  nexu-url: http://localhost:9795
  nexu-version: 1.23-SNAPSHOT
  nexu-download-url: /downloads/nexu-bundle.zip
  hide-wizard: true
  hide-auto-sign: true
  hide-send-sign-request: true
  #    archive-uri: smb://stockage.univ-rouen.fr/groupdirs/COMMUN/Demat/Archive/dev
  #    delay-before-cleaning : 0
  enable-su: true
  enable-splash: true
  version: '@project.version@'

tomcat:
  ajp:
    port: 6009

spring:
  # Static resources reloading during development
  profiles:
    active: dev
  data:
    ldap:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
    password: esup
    url: jdbc:postgresql://localhost:5432/esupsignature
    username: esupsignature
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  ldap:
    base: dc=univ-rouen,dc=fr
    password: Esupw7&56MZ
    urls: ldap://ldap.univ-rouen.fr
    username: cn=cons-esupSignature,dc=univ-rouen,dc=fr
  mail:
    host: smtp.univ-rouen.fr
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  security:
  #        oauth2:
  #            client:
  #                registration:
  #                    google:
  #                        client-id: 295837101524-b9kj77m2kp30ahr01kk5abaprr9r3h12.apps.googleusercontent.com
  #                        client-secret: OPeG_a0fifx1r5qcN5RONL_o
  #                        redirect-uri: http://dsi-7.univ-rouen.fr/login/oauth2/code/google
  #                        scope: profile, email
  servlet:
    multipart:
      enabled: true
      max-file-size: 1280KB
      max-request-size: 1280KB
      resolve-lazily: true

  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
    encoding: UTF-8
    mode: HTML



ldap:
  search-base: ou=people
  search-filter: (uid={0})
  affiliation-filter: member

mail:
  from: no-reply.esup-signature@univ-rouen.fr

sms:
  enable-sms : true
  service-name: SMSU
  url: https://smsu-api.univ-rouen.fr/
  username: sms-univ-rouen-account
  password: GeR4SmsK

extdb:
    data-sources:
        -
            name: test1
            driver-class-name: org.postgresql.Driver
            password: esup
            url: jdbc:postgresql://localhost:5432/esupsignature
            username: esupsignature
        -
            name: test2
            driver-class-name: org.postgresql.Driver
            password: esup
            url: jdbc:postgresql://localhost:5432/esupsignature
            username: esupsignature

fs:
  smb-login: esup-signature
  smb-password: BT28ap3R!
  smb-uri: smb://stockage.univ-rouen.fr/groupdirs/COMMUN/Demat
  vfs-uri: /tmp
#    cmis-uri: https://esup-signature.univ-rouen.fr:8083/nuxeo
#    cmis-login: Administrator
#    cmis-password: Administrator
#    cmis-respository-id: default
#    cmis-root-path: /default-domain/workspaces

pdf:
  convert-to-pdf-a: true
  height: 842
  path-to-g-s: /usr/bin/gs
  pdf-a-level: 2
  pdf-to-image-dpi: 72
  sign-width-threshold: 150
  width: 595

security:
  cas:
    domain: univ-rouen.fr
    group-search-base: ou=groups
    group-mapping-role-admin: ROLE_FOR.ESUP-SIGNATURE.ADMIN
    service: http://dsi-7.univ-rouen.fr/login/cas
    title: Compte Université de Rouen Normandie (CAS)
    url: https://cas.univ-rouen.fr
#  shib:
#    credentials-request-header: MEMBER
#    group-mapping-role-admin: cn=for.esup-signature.admin,ou=groups,dc=univ-rouen
#    idp-url: https://idp.univ-rouen.fr
#    principal-request-header: REMOTE_USER
#    title: Compte d’un autre établissement (Shibboleth)
#    domains-white-list-url: https://eduspot.renater.fr/eduspot/whitelist-eduspot.txt
  ws:
    ws-access-authorize-ips: 127.0.0.1

server:
  error:
    include-stacktrace: always
  port: 8080
  #max-http-header-size: 1MB

sign:
  cades-digest-algorithm: SHA256
  cades-signature-level: CAdES_BASELINE_T
  container-type: ASiC_E
  default-signature-form: XAdES
  pades-digest-algorithm: SHA256
  pades-signature-level: PAdES_BASELINE_T
  password-timeout: 60000
  signature-packaging: ENVELOPED
  xades-digest-algorithm: SHA256
  xades-signature-level: XAdES_BASELINE_T