ldap:
  search-base: ou=people
  user-object-classes: inetOrgPerson
  group-object-classes: groupOfNames
  ou-object-classes: organizationalUnit
  alias-object-classes: nisMailAlias
  users-search-filter: (&(|(displayName={0}*)(cn={0}*)(uid={0})(mail={0}*))(mail=*))
  group-search-base: ou=groups
  group-search-filter: member={0}
  all-groups-search-filter: cn=*{0}
  all-aliases-search-filter: (mail={0})
  user-id-search-filter: (uid={0})
  user-eppn-search-filter: (eduPersonPrincipalName={0})
  user-mail-search-filter: (mail={0})
  ou-search-filter: (supannCodeEntite={0})
  member-search-filter: (&(uid={0})({1}))
  members-of-group-search-filter: memberOf=cn={0},ou=groups,dc=univ-ville,dc=fr
  eppn-left-part-search-filter:
  mapping-filters-groups:
    student : "(eduPersonAffiliation:=student)"
    staff : "(eduPersonAffiliation:=staff)"
    affiliate : "(eduPersonAffiliation:=affiliate)"