// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.esupportail.esupsignature.domain;

import org.esupportail.esupsignature.domain.SignBook;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SignBook_Roo_Configurable {
    
    declare @type: SignBook: @Configurable;
    
}
