// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.esupportail.esupnfccarteculture.domain;

import org.esupportail.esupnfccarteculture.domain.TagLogGest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TagLogGest_Roo_Configurable {
    
    declare @type: TagLogGest: @Configurable;
    
}
