name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install ghostscript
      run: sudo apt-get update && sudo apt-get install -y docker-compose --fix-missing
    - name: Install ghostscript
      run: sudo apt-get update && sudo apt-get install -y ghostscript --fix-missing
    - name: Maven Surefire tests
      run: mvn -B clean package -Dspring.config.location=src/test/resources/application-test.yml -Djava.io.tmpdir=/tmp -DskipDockerCompose=false
    - name: Maven Selenium tests
      run: mvn verify -Dspring.config.location=src/test/resources/application-test.yml -DskipDockerCompose=false -DskipSurefire=true
